name: Build majestic runtime

on: push

jobs:

  ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # All these are already available in GitHub runner
    # - name: Install build tools
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y \
    #       autoconf \
    #       automake \
    #       libtool \
    #       make \
    #       g++

    - name: Build runtime
      working-directory: ./src/runtime/c
      run: |
        autoreconf -i
        ./configure
        make
        sudo make install

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      # with:
      #   ghc-version: '8.6'
      #   cabal-version: '2.4.1.0'

    - name: Run testsuite
      working-directory: ./src/runtime/haskell
      env:
        LD_LIBRARY_PATH: /usr/local/lib
      run: |
        cabal test --extra-lib-dirs=/usr/local/lib
